matrix:
    include:
        # - language: java
        #  jdk: oraclejdk8
        #  before_script:
        #    - cd backend
        #  before_install:
        #    - chmod +x backend/mvnw
          
        - language: android
          sudo: false
          env:
            global:
              - ANDROID_API_LEVEL=23
              - EMULATOR_API_LEVEL=24
              - ANDROID_BUILD_TOOLS_VERSION=25.0.2
              - ADB_INSTALL_TIMEOUT=10
              - ANDROID_ABI=armeabi-v7a
          before_script:
            - cd android_passengers
            - android-update-sdk --components=sys-img-$ABI-$API --accept-licenses='android-sdk-license-[0-9a-f]{8}'
          before_install:
            - mkdir "$ANDROID_HOME/licenses" || true
            - chmod +x android_passengers/gradlew
          android:
            components:
              - tools
              - platform-tools
              - android-$ANDROID_API_LEVEL
              - android-$EMULATOR_API_LEVEL
              - android-28
              - build-tools-$ANDROID_BUILD_TOOLS_VERSION
              - build-tools-28.0.2
              - build-tools-28.0.3
              - extra-android-m2repository
            licenses:
              - 'android-sdk-preview-license-.+'
              - 'android-sdk-license-.+'
              - 'google-gdk-license-.+'
          script: ./gradlew clean build test
              
        - language: android
          sudo: false
          env:
            global:
              - ANDROID_API_LEVEL=23
              - EMULATOR_API_LEVEL=24
              - ANDROID_BUILD_TOOLS_VERSION=25.0.2
              - ADB_INSTALL_TIMEOUT=10
              - ANDROID_ABI=armeabi-v7a
          before_script:
            - cd android_drivers
            - android-update-sdk --components=sys-img-$ABI-$API --accept-licenses='android-sdk-license-[0-9a-f]{8}'
          before_install:
            - mkdir "$ANDROID_HOME/licenses" || true
            - chmod +x android_drivers/gradlew
          android:
            components:
              - tools
              - platform-tools
              - android-$ANDROID_API_LEVEL
              - android-$EMULATOR_API_LEVEL
              - android-28
              - build-tools-$ANDROID_BUILD_TOOLS_VERSION
              - build-tools-28.0.2
              - build-tools-28.0.3
              - extra-android-m2repository
            licenses:
              - 'android-sdk-preview-license-.+'
              - 'android-sdk-license-.+'
              - 'google-gdk-license-.+'
          script: ./gradlew clean build test
